// UEMA 2007 compliance guard (audit P0-11, Phase 0 Task 0.5).
//
// Every outreach message TopFarms sends is a "commercial electronic message" under the
// NZ Unsolicited Electronic Messages Act 2007 — no B2B exemption, no low-volume exemption.
// ss 10-11 require accurate sender identification WITH contact details, and a functional
// unsubscribe facility, in EVERY message. Penalties reach $200k for an individual.
//
// Outreach copy is generated by two LLM prompts and one human template. This suite asserts
// the compliance instructions are present in all three, so a future prompt "tidy-up" that
// drops them fails CI instead of quietly sending non-compliant mail. Same static-source
// idiom as tests/webhook-secret-presence.test.ts.

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = resolve(__dirname, '..')

// The prompts are built as string arrays joined with '\n', so a single sentence can span
// several source lines with `',\n    '` between the words. Rejoin those seams so assertions
// match the logical prompt text rather than its source formatting.
const read = (p: string) =>
  readFileSync(resolve(ROOT, p), 'utf8').replace(/',\s*\n\s*'/g, ' ')

describe('Lane A — lead-draft-email SYSTEM_PROMPT (email)', () => {
  const source = read('supabase/functions/lead-draft-email/index.ts')

  it('names the Act so the rule cannot be mistaken for style guidance', () => {
    expect(source).toMatch(/Unsolicited\s+Electronic\s+Messages\s+Act\s+2007/)
  })

  it('mandates sender identification with a contact address', () => {
    expect(source).toContain('hello@topfarms.co.nz')
    expect(source).toMatch(/Harry Smith/)
  })

  it('mandates a functional unsubscribe line', () => {
    expect(source).toMatch(/Not interested\?\s*Reply/i)
    expect(source).toMatch(/won'?\\?'?t contact you again/i)
  })

  it('forbids reworking or omitting the compliance lines', () => {
    expect(source).toMatch(/[Nn]ever omit/)
  })
})

describe('Lane B — lead-intake draft prompt (Facebook DM)', () => {
  const source = read('supabase/functions/lead-intake/index.ts')

  it('names the Act and states that it covers instant messaging', () => {
    expect(source).toMatch(/Unsolicited\s+Electronic\s+Messages\s+Act\s+2007/)
    expect(source).toMatch(/instant messaging/i)
  })

  it('requires sender identification beyond the profile', () => {
    expect(source).toMatch(/SENDER IDENTIFICATION/)
    expect(source).toMatch(/profile alone is not sufficient/i)
  })

  it('requires an opt-out in the register of the message', () => {
    expect(source).toMatch(/OPT-OUT/)
    expect(source).toMatch(/won'?\\?'?t message again/i)
  })
})

describe('The human template — docs/OUTREACH-EMAIL.md', () => {
  const doc = read('docs/OUTREACH-EMAIL.md')

  it('carries sender identification and an unsubscribe line', () => {
    expect(doc).toContain('hello@topfarms.co.nz')
    expect(doc).toMatch(/Reply "no thanks"/)
  })

  it('explains that suppression — not deletion — is how an opt-out is honoured', () => {
    // A deleted lead gets re-harvested next run; only lead_suppression is durable.
    expect(doc).toMatch(/lead_suppression/)
  })

  it('carries no fabricated listing-volume claims', () => {
    // Truth pass 2026-07-30: prod holds 0 active jobs, so any claim about farms having
    // "listed this week" or candidate counts would be false at send time.
    expect(doc).not.toMatch(/farms have listed this week/i)
  })
})
