import { LegalLayout, LegalSection, LegalList } from './LegalLayout'

// Content source of truth: docs/legal/PRIVACY-POLICY.md (A-READY draft,
// pending legal review, FA-02/FA-11). Keep the two in sync.

export function Privacy() {
  return (
    <LegalLayout
      title="Privacy Policy"
      updated="Draft. Company details and effective date will be added when this policy is finalised."
    >
      <LegalSection heading="About this policy">
        <p>
          TopFarms is a New Zealand agricultural job marketplace at topfarms.co.nz. This policy
          explains what personal information we collect, why, who we share it with, and your
          rights under the New Zealand Privacy Act 2020. We have written it in plain English on
          purpose. Questions any time: hello@topfarms.co.nz.
        </p>
      </LegalSection>

      <LegalSection heading="1. What we collect">
        <p>If you are a job seeker (worker):</p>
        <LegalList
          items={[
            'Account details: name, email address, password (stored hashed by our auth provider).',
            'Profile details: skills, experience, work preferences, location, and your visa or residency status. Visa status is stored as a category only (NZ citizen, permanent resident, working holiday, student, or needs sponsorship). We do not store visa numbers or immigration case details.',
            'Contact details: phone number and email held in a separate, protected record (see the contact release section below).',
            'Documents you upload: CVs, certificates, references, and identity documents. All are stored in a private storage bucket that is not publicly accessible.',
          ]}
        />
        <p>If you are an employer:</p>
        <LegalList
          items={[
            'Account details: name, email address, password (stored hashed).',
            'Business details: farm or business name, location, verification documents and farm photos you provide, and the job listings you post.',
            'Payment details are handled by Stripe, our payment processor. We never see or store your full card number.',
          ]}
        />
        <p>
          For everyone: the authentication session cookie needed to keep you signed in, and
          standard server logs (IP address, timestamps) generated by our hosting providers.
        </p>
      </LegalSection>

      <LegalSection heading="2. Why we collect it">
        <LegalList
          items={[
            'To run the marketplace: matching workers with farm jobs, showing employers relevant candidates, and letting you apply for roles.',
            'To verify identity and eligibility to work, which helps keep the platform trustworthy for both sides.',
            'To generate AI assisted match explanations and candidate summaries (see the AI section below).',
            'To process payments (employer listing fees and placement fees).',
            'To send transactional email (application updates, verification outcomes, invoices).',
            'To meet our legal obligations.',
          ]}
        />
        <p>
          We do not sell personal information. We do not use your information for third party
          advertising.
        </p>
      </LegalSection>

      <LegalSection heading="3. AI processing: what does and does not reach the model">
        <p>
          We use Claude, an AI model operated by Anthropic (a US company), to generate match
          explanations and candidate summaries.
        </p>
        <p>
          What is sent to the AI: profile information such as skills, experience, work
          preferences, and your categorical visa status (for example "working holiday" or "needs
          sponsorship"). Visa status is included because eligibility to work is a core part of
          whether a match is realistic, and we want to be upfront that this category crosses to a
          US based provider.
        </p>
        <p>
          What is never sent to the AI: your identity documents, your contact details, and the
          contents of uploaded files. Identity documents are excluded from AI processing
          entirely.
        </p>
      </LegalSection>

      <LegalSection heading="4. How employers get your contact details">
        <p>
          Being honest about how this works: your phone number and email are held in a protected
          record that employers cannot see by default. An employer only receives your contact
          details after they acknowledge TopFarms' placement fee for hiring you. This is enforced
          at the database level, not just in the interface. Until that acknowledgement happens,
          employers see your profile and application but not your direct contact details.
        </p>
      </LegalSection>

      <LegalSection heading="5. Identity documents: extra protections">
        <LegalList
          items={[
            'Identity documents are never shown to employers. This is enforced at three independent layers: a database access policy, a server side allowlist in the function that issues document links, and a filter in the interface.',
            'Only TopFarms administrators can view them, via links that expire after 15 minutes.',
            'They are never sent to any AI model.',
          ]}
        />
      </LegalSection>

      <LegalSection heading="6. Who we share information with">
        <p>We use a small number of service providers to run TopFarms:</p>
        <LegalList
          items={[
            'Supabase (Australia, Sydney region): database, authentication, and file storage. Our primary data host.',
            'Vercel (US / global CDN): website hosting and delivery.',
            'Stripe (US / global): payment processing.',
            'Resend (US): transactional email delivery.',
            'Anthropic (US): AI match explanations and summaries, and parsing of public job post text in our admin leads pipeline.',
            'Firecrawl and Apify (US): admin only collection of publicly posted farm jobs (see the leads section below).',
            'Google and Facebook (US): sign in with Google or Facebook only, if you choose that option.',
          ]}
        />
        <p>
          Cross border note: your marketplace data lives in Australia. Some processing crosses to
          the United States as described above. Under the Privacy Act 2020 we remain responsible
          for information we disclose overseas, and we choose providers with strong security
          practices.
        </p>
      </LegalSection>

      <LegalSection heading="7. How long we keep information">
        <p>
          Marketplace data (your account and profile): we keep it while your account is active.
          Automatic deletion timelines for closed accounts are being built but are not yet live.
          Today, if you want your account and data deleted, email hello@topfarms.co.nz and we
          will do it manually.
        </p>
        <p>Leads pipeline (public job posts we collect for admin outreach, not marketplace data):</p>
        <LegalList
          items={[
            'Collected posts are staged and reviewed by a human before anything is kept.',
            'Rejected or stale staged items are purged after 30 days (automated weekly).',
            'Dead leads have personal information stripped after 6 months (automated monthly).',
            'If you ask us to stop contacting you, your details go on a suppression list that is honoured permanently. We keep the minimum needed to make sure we never contact you again.',
          ]}
        />
      </LegalSection>

      <LegalSection heading="8. The leads pipeline (people we contact who are not users)">
        <p>
          TopFarms staff collect publicly posted farm job listings (for example from public job
          boards) to invite farm employers to the platform. This is admin only tooling, separate
          from marketplace data. Every collected post is reviewed by a human before retention,
          retention is limited as set out above, and opting out is permanent. If we have
          contacted you and you would rather we did not, email hello@topfarms.co.nz.
        </p>
      </LegalSection>

      <LegalSection heading="9. Your rights">
        <p>Under the Privacy Act 2020 you can:</p>
        <LegalList
          items={[
            'Ask for a copy of the personal information we hold about you.',
            'Ask us to correct it if it is wrong.',
          ]}
        />
        <p>
          Email hello@topfarms.co.nz and we will respond within 20 working days as the Act
          requires. If you are not happy with how we have handled your information, you can
          complain to the Office of the Privacy Commissioner: privacy.org.nz or 0800 803 909.
        </p>
      </LegalSection>

      <LegalSection heading="10. If something goes wrong">
        <p>
          If a privacy breach occurs that is likely to cause serious harm, we will notify the
          Office of the Privacy Commissioner and affected people as soon as practicable, as the
          Privacy Act 2020 requires.
        </p>
      </LegalSection>

      <LegalSection heading="11. Cookies">
        <p>
          We keep it minimal: TopFarms uses the cookie and session storage needed to keep you
          signed in, set by our authentication provider. We do not run third party advertising or
          tracking cookies.
        </p>
      </LegalSection>

      <LegalSection heading="12. Security">
        <p>
          Access to data is restricted by row level database policies (each user can only reach
          their own records), documents live in private storage buckets, admin access to
          sensitive documents uses short lived links, and administrative actions are recorded in
          an audit log.
        </p>
      </LegalSection>

      <LegalSection heading="13. Changes and contact">
        <p>
          If we change this policy in a way that matters, we will post the updated version here
          with a new date, and for significant changes we will email account holders. Privacy
          questions, access or correction requests, and opt outs: hello@topfarms.co.nz.
        </p>
      </LegalSection>
    </LegalLayout>
  )
}
