#!/usr/bin/env node
// Phase 4.1 contrast gate. Parses the design tokens out of src/index.css,
// computes WCAG 2.x contrast for every text-role token pair in use, prints the
// table (markdown — redirect to docs/design/contrast.md to regenerate the
// artefact), and exits non-zero if any TEXT pair is below 4.5:1.
//
//   node scripts/contrast.mjs            # table + gate
//   node scripts/contrast.mjs > docs/design/contrast.md   # regenerate artefact
import { readFileSync } from 'node:fs'

const css = readFileSync(new URL('../src/index.css', import.meta.url), 'utf8')

// Token map. Resolves one level of var() indirection (brand-700 → brand-hover).
const raw = {}
for (const [, name, value] of css.matchAll(/(--color-[\w-]+):\s*([^;]+);/g)) {
  raw[name] = value.trim()
}
const tokens = {}
for (const [name, value] of Object.entries(raw)) {
  const ref = value.match(/^var\((--color-[\w-]+)\)$/)
  tokens[name] = ref ? raw[ref[1]] : value
}

function lum(hex) {
  const m = hex.match(/^#([0-9a-f]{6})$/i)
  if (!m) throw new Error(`not a 6-digit hex colour: ${hex}`)
  const [r, g, b] = [0, 2, 4].map((i) => {
    const c = parseInt(m[1].slice(i, i + 2), 16) / 255
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
  })
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

function ratio(fg, bg) {
  const [hi, lo] = [lum(tokens[`--color-${fg}`]), lum(tokens[`--color-${bg}`])].sort((a, b) => b - a)
  return (hi + 0.05) / (lo + 0.05)
}

// kind 'text' → gated at 4.5:1 (WCAG AA normal text).
// kind 'large' → gated at 3:1 (AA large text — ≥24px or ≥18.7px bold only).
// kind 'info' → recorded, not gated (fills, borders, decorative marks).
const PAIRS = [
  // Body text on every surface it appears on
  ['text', 'surface', 'text', 'body text on cards'],
  ['text', 'bg', 'text', 'body text on page bg'],
  ['text', 'surface-2', 'text', 'body text on tinted panels'],
  ['text-muted', 'surface', 'text', 'secondary text on cards'],
  ['text-muted', 'bg', 'text', 'secondary text on page bg'],
  ['text-muted', 'surface-2', 'text', 'secondary text on tinted panels'],
  ['text-muted', 'border', 'text', 'terminal Applied badge (SearchJobCard)'],
  ['text-subtle', 'surface', 'text', 'tertiary text on cards (darkened Phase 4.1)'],
  ['text-subtle', 'bg', 'text', 'tertiary text on page bg'],
  ['text-subtle', 'surface-2', 'text', 'tertiary text on tinted panels'],
  // CTAs — brand demoted to fill/border; text & CTA fills use brand-hover
  ['text-on-brand', 'brand-hover', 'text', 'primary Button default (Phase 4.1 demotion)'],
  ['text-on-brand', 'brand-900', 'text', 'primary Button hover state'],
  ['brand-hover', 'surface', 'text', 'brand-coloured links / labels on white'],
  ['brand-hover', 'bg', 'text', 'brand-coloured links on page bg'],
  ['brand-hover', 'surface-2', 'text', 'brand-coloured links on tinted panels'],
  // Semantic text-on-tint tokens — each against its *-bg partner
  ['success-text-on-bg', 'success-bg', 'text', 'green Tag / MatchCircle high band'],
  ['warn-text-on-bg', 'warn-bg', 'text', 'warn Tag / MatchCircle mid band'],
  ['info-text-on-bg', 'info-bg', 'text', 'blue Tag (visa sponsorship)'],
  ['ai-text-on-bg', 'ai-bg', 'text', 'purple Tag / AI info boxes'],
  ['danger-text-on-bg', 'danger-bg', 'text', 'red Tag / error boxes'],
  // Semantic colours still used as text directly on light surfaces
  ['danger', 'surface', 'text', 'inline error text on white'],
  ['danger', 'bg', 'text', 'inline error text on page bg'],
  // Retired-as-text pairs, kept in the table as the record of WHY (all fail)
  ['brand', 'surface', 'info', 'RETIRED as text: was every primary CTA (white on brand 3.30)'],
  ['text-on-brand', 'brand', 'info', 'RETIRED: old primary Button default'],
  ['warn', 'surface', 'info', 'fill/icon only — never text'],
  ['info', 'surface', 'info', 'fill/icon only — never text'],
  ['ai', 'surface', 'info', 'fill/icon only — never text'],
  ['success', 'success-bg', 'info', 'RETIRED as text: old green Tag (2.94, prompt said pass — it does not)'],
]

const rows = []
let failed = 0
for (const [fg, bg, kind, note] of PAIRS) {
  const r = ratio(fg, bg)
  const min = kind === 'text' ? 4.5 : kind === 'large' ? 3 : null
  const verdict = min === null ? 'n/a (not text)' : r >= min ? 'PASS' : 'FAIL'
  if (verdict === 'FAIL') failed++
  rows.push({ fg, bg, hexFg: tokens[`--color-${fg}`], hexBg: tokens[`--color-${bg}`], r, kind, verdict, note })
}

function t(name) {
  return tokens[`--color-${name}`]
}
console.log('# Token contrast — computed, not quoted')
console.log()
console.log(`Generated by \`node scripts/contrast.mjs\` from \`src/index.css\`.`)
console.log('Text pairs are gated at 4.5:1 (WCAG AA); the script exits non-zero on any text-pair failure.')
console.log('Rows marked `n/a (not text)` are fills/borders recorded for the audit trail — the token contract')
console.log('(src/index.css §Semantic) forbids using them as text.')
console.log()
console.log('| Foreground | Background | Ratio | Gate | Verdict | Where |')
console.log('|---|---|---|---|---|---|')
for (const row of rows) {
  const gate = row.kind === 'text' ? '4.5' : row.kind === 'large' ? '3.0' : '—'
  console.log(
    `| \`${row.fg}\` ${t(row.fg)} | \`${row.bg}\` ${t(row.bg)} | ${row.r.toFixed(2)} | ${gate} | ${row.verdict} | ${row.note} |`,
  )
}
console.log()
console.log(`Text pairs failing: ${failed}`)

// Source scan: a raw semantic colour used as TEXT on the same line as a tinted
// background is exactly the pattern that shipped the 1.93:1 orange Tag. The
// *-text-on-bg tokens exist for this; fail the gate if the raw pattern returns.
import { execSync } from 'node:child_process'
const rawOnTint = execSync(
  String.raw`grep -rnE 'text-(warn|info|ai|danger|brand)([ "'\''/]|$)' src --include='*.tsx' | grep -E 'bg-(warn|info|ai|danger|success)-bg|bg-brand-50|bg-brand/10|rgba\(74,124,47|rgba\(220,53,69' | grep -vE 'text-(warn|info|ai|danger|success|brand)-text-on-bg|hover:text|// ' || true`,
  { cwd: new URL('..', import.meta.url).pathname, encoding: 'utf8' },
).trim()
if (rawOnTint) {
  console.log()
  console.log('Raw semantic text colour on a tinted background (use *-text-on-bg):')
  console.log(rawOnTint)
  process.exit(1)
}
if (failed > 0) process.exit(1)
